### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tomsteenbakkers** [ErwinSteffens/p1-influxdb#1]
Hi Erwin,

I have Homebridge (running on node) running on a RaspberryPi to control my house with HomeKit. I have connected my Smart Meter with Homebridge zo I can store the data in HomeKit.

Now I want to store also the P1 data in influx so I can use Grafana to analyse the data.

How do I install your software? I'm not an expert on node hence the question.

**Comment by ErwinSteffens** [comment]
Hi Tom,

You can clone it and start it with `node index.js` but it is not very obvius and there is not a lot of documentation for it. Feel free to add some or to add a dockerfile which can be build/used for running it on a PI. 

Not sure if you can use it in combination with Homebridge as you already have de serial port connected to Homebridge and it cannot be used anymore by this tool.

**Comment by tomsteenbakkers** [comment]
I have tried it but Homebridge plugin claim the p1 port exclusive. Need to figure out a new solution ;>
